### ISSUE TITLE
Accessible Addons deployment fails after KKP upgrade to v.2.20

### ISSUE THREAD

**Issue by mihiragrawal** [kubermatic/kubermatic#9976] opened 2022-06-03 13:58 UTC
### What happened?

After KKP upgrade to v.2.20, accessible addons fails to deploy and says,
```
failed to reconcile Addon "ingress-nginx": failed to deploy the addon manifests into the cluster: failed to execute '/usr/local/bin/kubectl-1.22 --kubeconfig /tmp/cluster-z88t5clgxz-addon-ingress-nginx-kubeconfig apply --prune --filename /tmp/cluster-z88t5clgxz-ingress-nginx.yaml --selector kubermatic-addon=ingress-nginx' for addon ingress-nginx of cluster z88t5clgxz: exit status 1 namespace/ingress-nginx unchanged serviceaccount/ingress-nginx unchanged configmap/ingress-nginx-controller unchanged clusterrole.rbac.authorization.k8s.io/ingress-nginx unchanged clusterrolebinding.rbac.authorization.k8s.io/ingress-nginx unchanged role.rbac.authorization.k8s.io/ingress-nginx unchanged rolebinding.rbac.authorization.k8s.io/ingress-nginx unchanged service/ingress-nginx-controller-admission unchanged service/ingress-nginx-controller configured error: error validating "/tmp/cluster-z88t5clgxz-ingress-nginx.yaml": error validating data: ValidationError(Deployment.spec.replicas): invalid type for io.k8s.api.apps.v1.DeploymentSpec.replicas: got "string", expected "integer"; if you choose to ignore these errors, turn validation off with --validate=false	z88t5clgxz	Cluster	4	a few seconds ago
```

I have confirmed the addon manifest parsed as the below value in a seed-controller-manager pod. Which is wrong, but I don't know why.

```yaml
spec:
  replicas: <no value>
```

My addon spec  is,

```yaml
spec:
  replicas: {{ .Variables.replicas}}
```

and addonconfig is,

```yaml
apiVersion: kubermatic.k8c.io/v1
kind: AddonConfig
metadata:
  name: ingress-nginx
spec:
  formSpec:
    - displayName: Replicas
      internalName: replicas
```
PS: Initially AddonConfigwas on an old API [kubermatic.k8s.io](http://kubermatic.k8s.io/) which I just updated to [kubermatic.k8c.io](http://kubermatic.k8c.io/)

### Expected behavior

Till version v.2.19, able to deploy same addons , which should work as well. 

### How to reproduce the issue?

- Create an Accessible addon with configurable variables, as I did in above case.
- Create a docker image out of it and use it in your KKP config. Which will eventually used by seed-controller-manager. 
- Add that Accessible addon to your cluster. 

### How is your environment configured?

- KKP version: v.2.20.2
- Shared or separate master/seed clusters?: separate

### What cloud provider are you running on?

GCP

### What operating system are you running in your user cluster?

Ubuntu 20.04,

**Comment by xrstf** [comment] 2022-06-07 14:19
This is ultimately caused by, as you wrote, no addon variable `replicas` being defined in the `Addon` object. However, in KKP 2.20.x you are **not able** to set addon variables because of a bug that is fixed in #10010 (will be released in KKP 2.20.4).

But even with the fix, if your custom nginx addon refers to a `replicas` variable, you better make sure you have an `AddonConfig` that defines a field for the replicas, or rewrite your manifests to do `{{ .Variables.replicas | default 3 }}` or so.

**Comment by toschneck** [comment] 2022-06-15 12:03
ok so we need to wait for the `2.20.4` release and test again @mihiragrawal

**Comment by xrstf** [comment] 2022-06-22 12:59
2.20.4 has just been released.

**Closed as completed** 2022-08-09 09:02 UTC
Labels: kind/bug
