### ISSUE TITLE
Network resource group for machine controller

### ISSUE THREAD

**Issue by zreigz** [kubermatic/kubermatic#6314] opened 2020-12-16 10:16 UTC

**Comment by moadqassem** [comment] 2021-01-13 11:47
This ticket is a duplicate of this one https://app.zenhub.com/workspaces/work-in-progress---the-a-team-5fa971db111c0d0018ce0008/issues/kubermatic/machine-controller/836.

**Closed as completed by moadqassem** 2021-01-13 11:47 UTC
