### ISSUE TITLE
Define/Modify Application Catalog via UI(from KKP Dashboard)

### ISSUE THREAD

**Issue by archups** [kubermatic/kubermatic#12526] opened 2023-08-01 06:02 UTC
### Description of the feature you would like to add / User story

As a KKP admin user, I would like to define or modify the Application Catalog (i.e. create or update ApplicationDefinitions for the applications) via KKP Dashboard (UI),
in order to make KKP more user friendly from applications management perspective.

### Solution details

- Provide possibility for KKP admin to define the Application Catalog (create ApplicationDefinition) via KKP Dashboard(UI).
- Provide possibility for KKP admin to modify an existing application from the Application Catalog (create ApplicationDefinition) via KKP Dashboard(UI).

### Use cases

- While working together with end users,  KKP admin can setup the Application Catalog on the fly (i.e. define or modify the application catalog from KKP Dashboard) which makes end user understand more easily what admin is doing and give quick feedback on what is expected.
- End user doesn't need to know CRDs specific to the Application Catalog.

**Comment by SimonTheLeg** [comment] 2023-08-01 09:12
closed as duplicate of https://github.com/kubermatic/kubermatic/issues/11328

**Closed as completed by SimonTheLeg** 2023-08-01 09:12 UTC
Labels: kind/feature, sig/app-management, ee
