### ISSUE TITLE
Debug/Fix KKP 2.19 Test Env

### ISSUE THREAD

**Issue by dermorz** [kubermatic/kubermatic#8728] opened 2022-01-14 10:17 UTC
On 2022-01-13 we noticed that when creating new clusters, they were not able to get up machine deployments. We need to figure out what's happening to re-enable testing that involves creating new clusters.

This is what we know so far:
- Currently already existing clusters before this issue appeared are not affected. 
- It seems that the issues started when we enabled the feature gate for Konnectivity, but this might also coincidental.
- We most probably can rule out AWS issues (like being limited by quota), because:
  - On the kink-environment (kkp in kkp) we use the same aws credentials and vpc and on that KKP instance everything works as expected
  - We have the same issue when creating a user cluster on GCP
- We have had a look into the commits between [alpha.5...alpha.6](https://github.com/kubermatic/kubermatic/compare/v2.19.0-alpha.5...v2.19.0-alpha.6) and could not find any changes that would affect this area
- logs in the affected clusters
	- machine controller constantly spams but we could not infer anything from it
		```log
		Unable to get node for machine nostalgic-albattani-b658866f7-27p29, machine has no node ref
		```
	- usercluster-controller is not showing anything out of the ordinary
		```log
	  usercluster-controller-574fbbd88c-bsz9q usercluster-controller {"level":"info","time":"2022-01-14T08:01:47.032Z","logger":"controller.kubermatic_flatcar_controller","caller":"controller/controller.go:220","msg":"Starting workers","worker count":1}
	  usercluster-controller-574fbbd88c-bsz9q usercluster-controller {"level":"info","time":"2022-01-14T08:01:47.063Z","logger":"controller.user-cluster-controller","caller":"controller/controller.go:220","msg":"Starting workers","worker count":1}
	  usercluster-controller-574fbbd88c-bsz9q usercluster-controller {"level":"info","time":"2022-01-14T08:01:47.063Z","logger":"controller.cluster_role_label_controller","caller":"controller/controller.go:220","msg":"Starting workers","worker count":1}
	  usercluster-controller-574fbbd88c-bsz9q usercluster-controller {"level":"info","time":"2022-01-14T08:01:47.063Z","logger":"controller.rbac-user-cluster-controller","caller":"controller/controller.go:220","msg":"Starting workers","worker count":1}
	  usercluster-controller-574fbbd88c-bsz9q usercluster-controller {"level":"info","time":"2022-01-14T08:01:47.063Z","logger":"controller.node_label_controller","caller":"controller/controller.go:220","msg":"Starting workers","worker count":1}
	  usercluster-controller-574fbbd88c-bsz9q usercluster-controller {"level":"info","time":"2022-01-14T08:01:47.065Z","logger":"controller.clone_role_controller","caller":"controller/controller.go:220","msg":"Starting workers","worker count":1}
	  usercluster-controller-574fbbd88c-bsz9q usercluster-controller {"level":"info","time":"2022-01-14T08:01:47.065Z","logger":"controller.owner_binding_controller","caller":"controller/controller.go:220","msg":"Starting workers","worker count":1}
	  usercluster-controller-574fbbd88c-bsz9q usercluster-controller {"level":"info","time":"2022-01-14T08:01:48.386Z","logger":"controller-runtime.healthz","caller":"logr@v1.2.0/logr.go:249","msg":"healthz check failed","statuses":[{},{}]}
		```
	- etcd seems to be fine
	- OpenVPN seems fine
	- controller-manager just logs out that it cannot find the metrics for the nodes, which fits with the overall issue
		```log
		resource_quota_controller.go:409] unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request
		```
	- apiServer is not showing any issues

**Comment by SimonTheLeg** [comment] 2022-01-14 11:09
we did find in the DNS logs that something is using the wrong DNS domain
```bash
# notice that the .sv.cluster.local is twice in the URL. Looks like a templating mistake
[ERROR] plugin/errors: 2 metrics-server.cluster-lcsnkrllln.svc.cluster.local.cluster.local. A: read udp 10.20.0.18:42553->10.240.16.10:53: i/o timeout
```
		
This does not occur in our kink cluster and most likely is related to the controller-manager error. Will investigate now if this is related to the overall issue as well.

**Comment by SimonTheLeg** [comment] 2022-01-14 16:18
What we know so far:
* we don't think the change is related to the CIDR update. We can see that IP-ranges are correctly resolved in the cluster
* we have observed a lot of timeouts in the kubermatic-api server, which point to not active IPs anymore. This leads us to believe that there might be some old target groups in our ELB load-balancer which get returned. We will investigate this further
```log

kubermatic-api-66ff695cf9-xpdww api 172.27.5.79 - - [14/Jan/2022:16:10:39 +0000] "GET /api/v2/projects/54pzfbzl5h/clusters/smgjbmwtvh/events HTTP/1.1" 500 52 "https://<sanitized>kubermatic.io/projects/54pzfbzl5h/clusters/smgjbmwtvh" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
kubermatic-api-66ff695cf9-xpdww api err="failed to create restMapper: Get \"https://gxqjjnj4c4.<sanitized>kubermatic.io:31383/api?timeout=32s\": dial tcp 3.126.133.148:31383: i/o timeout"
kubermatic-api-66ff695cf9-xpdww api 172.27.4.20 - - [14/Jan/2022:16:10:25 +0000] "GET /api/v2/projects/9p5vrwltp9/clusters/gxqjjnj4c4/machinedeployments HTTP/1.1" 500 201 "https://<sanitized>kubermatic.io/projects/9p5vrwltp9/clusters" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15"
kubermatic-api-66ff695cf9-xpdww api err="failed to create restMapper: Get \"https://smgjbmwtvh.<sanitized>kubermatic.io:32436/api?timeout=32s\": dial tcp 3.124.120.115:32436: i/o timeout"
kubermatic-api-66ff695cf9-xpdww api 172.27.5.79 - - [14/Jan/2022:16:10:39 +0000] "GET /api/v2/projects/54pzfbzl5h/clusters/smgjbmwtvh/upgrades HTTP/1.1" 500 201 "https://<sanitized>kubermatic.io/projects/54pzfbzl5h/clusters/smgjbmwtvh" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
kubermatic-api-66ff695cf9-xpdww api err="failed to create restMapper: Get \"https://smgjbmwtvh.<sanitized>kubermatic.io:32436/api?timeout=32s\": dial tcp 3.124.120.115:32436: i/o timeout"
kubermatic-api-66ff695cf9-xpdww api 172.27.5.79 - - [14/Jan/2022:16:10:39 +0000] "GET /api/v2/projects/54pzfbzl5h/clusters/smgjbmwtvh/machinedeployments HTTP/1.1" 500 201 "https://<sanitized>kubermatic.io/projects/54pzfbzl5h/clusters/smgjbmwtvh" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
kubermatic-api-66ff695cf9-xpdww api err="not authorized"
kubermatic-api-66ff695cf9-xpdww api 172.27.4.20 - - [14/Jan/2022:16:11:41 +0000] "GET /api/v1/projects?displayAll=false HTTP/1.1" 401 172 "https://<sanitized>kubermatic.io/projects" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36"
kubermatic-api-66ff695cf9-xpdww api err="failed to create restMapper: Get \"https://lcsnkrllln.<sanitized>kubermatic.io:30799/api?timeout=32s\": dial tcp 3.126.133.148:30799: i/o timeout"
kubermatic-api-66ff695cf9-xpdww api 172.27.4.20 - - [14/Jan/2022:16:11:27 +0000] "GET /api/v2/projects/9p5vrwltp9/clusters/lcsnkrllln/machinedeployments HTTP/1.1" 500 201 "https://<sanitized>kubermatic.io/projects/9p5vrwltp9/clusters" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15"
kubermatic-api-66ff695cf9-xpdww api err="failed to create restMapper: Get \"https://gxqjjnj4c4.<sanitized>kubermatic.io:31383/api?timeout=32s\": dial tcp 3.126.133.148:31383: i/o timeout"
kubermatic-api-66ff695cf9-xpdww api 172.27.4.20 - - [14/Jan/2022:16:11:35 +0000] "GET /api/v2/projects/9p5vrwltp9/clusters/gxqjjnj4c4/machinedeployments HTTP/1.1" 500 201 "https://<sanitized>kubermatic.io/projects/9p5vrwltp9/clusters" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15"
kubermatic-api-66ff695cf9-xpdww api err="failed to create restMapper: Get \"https://smgjbmwtvh.<sanitized>kubermatic.io:32436/api?timeout=32s\": dial tcp 18.198.195.218:32436: i/o timeout"
kubermatic-api-66ff695cf9-xpdww api 172.27.5.79 - - [14/Jan/2022:16:11:39 +0000] "GET /api/v2/projects/54pzfbzl5h/clusters/smgjbmwtvh/upgrades HTTP/1.1" 500 202 "https://<sanitized>kubermatic.io/projects/54pzfbzl5h/clusters/smgjbmwtvh" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
kubermatic-api-66ff695cf9-xpdww api err="failed to create restMapper: Get \"https://smgjbmwtvh.<sanitized>kubermatic.io:32436/api?timeout=32s\": dial tcp 18.198.195.218:32436: i/o timeout"
kubermatic-api-66ff695cf9-xpdww api 172.27.5.79 - - [14/Jan/2022:16:11:39 +0000] "GET /api/v2/projects/54pzfbzl5h/clusters/smgjbmwtvh/machinedeployments HTTP/1.1" 500 202 "https://<sanitized>kubermatic.io/projects/54pzfbzl5h/clusters/smgjbmwtvh" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
kubermatic-api-66ff695cf9-xpdww api err="Get \"https://objective-hopper-api-lb-1210365532.eu-central-1.elb.amazonaws.com:6443/api/v1/events?fieldSelector=involvedObject.name%3Dsmgjbmwtvh\": context canceled"
kubermatic-api-66ff695cf9-xpdww api 172.27.5.79 - - [14/Jan/2022:16:12:39 +0000] "GET /api/v2/projects/54pzfbzl5h/clusters/smgjbmwtvh/events HTTP/1.1" 500 201 "https://<sanitized>kubermatic.io/projects/54pzfbzl5h/clusters/smgjbmwtvh" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
kubermatic-api-66ff695cf9-xpdww api err="failed to create restMapper: Get \"https://lcsnkrllln.<sanitized>kubermatic.io:30799/api?timeout=32s\": dial tcp 3.124.120.115:30799: i/o timeout"
kubermatic-api-66ff695cf9-xpdww api 172.27.4.20 - - [14/Jan/2022:16:12:36 +0000] "GET /api/v2/projects/9p5vrwltp9/clusters/lcsnkrllln/machinedeployments HTTP/1.1" 500 201 "https://<sanitized>kubermatic.io/projects/9p5vrwltp9/clusters" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15"
kubermatic-api-66ff695cf9-xpdww api err="failed to create restMapper: Get \"https://smgjbmwtvh.<sanitized>kubermatic.io:32436/api?timeout=32s\": dial tcp 3.126.133.148:32436: i/o timeout"
kubermatic-api-66ff695cf9-xpdww api 172.27.4.20 - - [14/Jan/2022:16:12:39 +0000] "GET /api/v2/projects/54pzfbzl5h/clusters/smgjbmwtvh/metrics HTTP/1.1" 500 201 "https://<sanitized>kubermatic.io/projects/54pzfbzl5h/clusters/smgjbmwtvh" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
kubermatic-api-66ff695cf9-xpdww api err="failed to create restMapper: Get \"https://gxqjjnj4c4.<sanitized>kubermatic.io:31383/api?timeout=32s\": dial tcp 3.126.133.148:31383: i/o timeout"
kubermatic-api-66ff695cf9-xpdww api 172.27.4.20 - - [14/Jan/2022:16:13:39 +0000] "GET /api/v2/projects/9p5vrwltp9/clusters/gxqjjnj4c4/machinedeployments HTTP/1.1" 500 201 "https://<sanitized>kubermatic.io/projects/9p5vrwltp9/clusters" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15"
kubermatic-api-66ff695cf9-xpdww api 172.27.4.20 - - [14/Jan/2022:16:13:39 +0000] "GET /api/v2/projects/54pzfbzl5h/clusters/smgjbmwtvh/nodes?hideInitialConditions=true HTTP/1.1" 500 201 "https://<sanitized>kubermatic.io/projects/54pzfbzl5h/clusters/smgjbmwtvh" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
kubermatic-api-66ff695cf9-xpdww api err="failed to create restMapper: Get \"https://smgjbmwtvh.<sanitized>kubermatic.io:32436/api?timeout=32s\": dial tcp 3.124.120.115:32436: i/o timeout"
kubermatic-api-66ff695cf9-xpdww api 172.27.4.20 - - [14/Jan/2022:16:13:39 +0000] "GET /api/v2/projects/54pzfbzl5h/clusters/smgjbmwtvh/metrics HTTP/1.1" 500 201 "https://<sanitized>kubermatic.io/projects/54pzfbzl5h/clusters/smgjbmwtvh" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
kubermatic-api-66ff695cf9-xpdww api err="failed to create restMapper: Get \"https://smgjbmwtvh.<sanitized>kubermatic.io:32436/api?timeout=32s\": dial tcp 3.124.120.115:32436: i/o timeout"

```

**Comment by SimonTheLeg** [comment] 2022-01-17 09:10
The issue is related to the AWS security group limit. Due to it, no new security groups get created that allow connections to target groups in the AWS LoadBalancer (no connection also means no passing healthchecks, means no available nodes, means no routing). This in turn is the culprit that after exceeding the quota, new cluster worker nodes cannot be reached.
You can see this in CloudTrail by filtering for `eventName: "AuthorizeSecurityGroupIngress"` and `"errorCode": "Client.RulesPerSecurityGroupLimitExceeded"`.
In order to bandaid the solution I have now requested a quota increase at AWS, which triples our maximum number of clusters.

Overall this issue has no relation to the new KKP version, but might have quota implications if a customer wants to run KKP on AWS using nodeport. We should take a closer look at this after the release is finished.

**Closed as completed** 2022-01-17 09:25 UTC
