### ISSUE TITLE
Zone Topology is not respected for etcd / api server of user cluster control plane

### ISSUE THREAD

**Issue by toschneck** [kubermatic/kubermatic#12171] opened 2023-04-12 18:40 UTC
### What happened?

Currently it seams that the cluster don't go spreaded via AZ zones, as the cluster-id ist not added to the affinity rule
<img width="326" alt="kubermatic-dev… 2023-04-12 20-31-44" src="https://user-images.githubusercontent.com/4659261/231552573-1fa9310c-1ab2-45a4-9374-eaa6d80d1c41.png">
<img width="436" alt="kubermatic-dev… 2023-04-12 20-36-42" src="https://user-images.githubusercontent.com/4659261/231553205-00ddca37-f14f-4c42-b5c2-09f71129b02c.png">

<img width="521" alt="kubermatic-dev… 2023-04-12 20-34-24" src="https://user-images.githubusercontent.com/4659261/231552651-27a30acd-7b92-43e0-91a9-e767bfba427a.png">

<img width="619" alt="kubermatic-dev… 2023-04-12 20-34-39" src="https://user-images.githubusercontent.com/4659261/231552913-636fbbf8-a154-4c88-8a18-05043d6aa93d.png">

### Expected behavior

Each ETCD / API instance of one Cluster should be spread as much as possible to the availability zones. This means I expect as user the each etcd runs (if resource are there) are spreaded to AZ zones. Same for API server

### How to reproduce the issue?

Deploy clusters and investigate zone / node alignement of the  pods at a user cluster namespace

### How is your environment configured?

- KKP version: 2.22.1
- Shared or separate master/seed clusters?: shared

### Provide your KKP manifest here (if applicable)

[Run-2](https://github.com/kubermatic/sig-cs-infra/tree/main/lab.kubermatic.io/run-2.lab.kubermatic.io)

<details>

```yaml
# paste manifest here
```

</details>

### What cloud provider are you running on?

Seed on GCE

### What operating system are you running in your user cluster?

doesn't matter

**Comment by embik** [comment] 2023-04-26 06:47
There is a fix for this in #12197, however it is very important to recognise that there is no guarantee this fixes the specific problem pointed out for run-2 - if no nodes are available for scheduling, etcds and kube-apiservers will continue to run in the same zone.

**Comment by embik** [comment] 2023-05-02 12:13
Turns out this is not actually a bug. As per https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity:

> If omitted or empty, namespaces defaults to the namespace of the Pod where the affinity/anti-affinity definition appears.

This means the rules highlighted as "faulty" were always only applied within the `cluster-<cluster ID>` namespaces against other Pods within that same namespace; which means, `app=etcd` is sufficient to make sure that etcds of the same cluster are preferred to not be scheduled onto the same node.

The rules look confusing and suggest that zone anti-affinity is not specified for same-cluster pods, but it's the original per-node anti-affinity that's actually incorrect. It doesn't produce incorrect scheduling, but the same results could be achieved with only one anti-affinity rule.

I'll close this issue since it's not a bug (as mentioned before; the observed behaviour in the run-2 environment means that at the time of scheduling, there wasn't the possibility to satisfy the anti-affinity rules), but I'll make sure we simplify the existing rules.

**Closed as not planned by embik** 2023-05-02 12:13 UTC
Labels: kind/bug
