### ISSUE TITLE
Test migrating the expose strategy for existing clusters - Test Release KKP 2.22

### ISSUE THREAD

**Issue by rastislavs** [kubermatic/kubermatic#11831] opened 2023-02-06 09:55 UTC
- Create a new user cluster with the default expose strategy
- Manually migrate the user cluster to a different expose strategy - follow the guide at https://docs.kubermatic.com/kubermatic/main/tutorials-howtos/networking/expose-strategies/#migrating-the-expose-strategy-for-existing-clusters

**Comment by embik** [comment] 2023-02-07 08:10
Note: When trying to go from `Tunneling` to `LoadBalancer`, just changing the field returns:

```
error: clusters.kubermatic.k8c.io "gxrncr6wvw" could not be patched: admission webhook "clusters.kubermatic.io" denied the request: spec.TunnelingAgentIP: Forbidden: Tunneling agent IP can be configured only for Tunneling Expose strategy
```

**Comment by rastislavs** [comment] 2023-02-07 08:17
> Removing the TunnelingAgentIP field makes it proceed though.

Thanks, that is the correct approach, will update the docs accordingly.

**Comment by rastislavs** [comment] 2023-02-07 08:46
Docs update: https://github.com/kubermatic/docs/pull/1346

**Comment by embik** [comment] 2023-02-07 09:59
It seems that with the method given in the linked docs, the old machines are not getting cleaned up:

```
k get nodes
NAME                                        STATUS                        ROLES    AGE   VERSION
ljzbbd9zz6-worker-wll22v-5fb64d4984-6njn6   Ready                         <none>   21m   v1.25.5
ljzbbd9zz6-worker-wll22v-5fb64d4984-bshdj   Ready                         <none>   14m   v1.25.5
ljzbbd9zz6-worker-wll22v-7695f45d85-j85v2   NotReady,SchedulingDisabled   <none>   48m   v1.25.5
ljzbbd9zz6-worker-wll22v-7695f45d85-kbsgk   NotReady,SchedulingDisabled   <none>   41m   v1.25.5
```

there's also nothing in `machine-controller` logs hinting as to why they aren't cleaned up, besides maybe 

```
E0207 09:44:56.138149       1 machinedeployment_controller.go:135] Failed to reconcile MachineDeployment "kube-system/ljzbbd9zz6-worker-wll22v": Operation cannot be fulfilled on machinedeployments.cluster.k8s.io "ljzbbd9zz6-worker-wll22v": the object has been modified; please apply your changes to the latest version and try again
```

I'll keep investigating and see if this is reproducible.

**Comment by embik** [comment] 2023-02-07 14:08
I was able to migrate between all expose strategies, but NotReady nodes already stuck. it looks like machine-controller doesn't clean them up properly. @rastislavs should I add a note to the migration docs saying that dead `Node` objects need to be deleted?

**Comment by rastislavs** [comment] 2023-02-07 14:11
> should I add a note to the migration docs saying that dead `Node` objects need to be deleted?

Yeah, if this is consistent behaviour, let's add that into the docs. Thanks!

**Comment by embik** [comment] 2023-02-07 14:27
Closing, everything looks good and documentation has been adjusted.

**Closed as completed by embik** 2023-02-07 14:27 UTC
