### ISSUE TITLE
Test UserCluster MLA upgrade - Test Release 2.22

### ISSUE THREAD

**Issue by wurbanski** [kubermatic/kubermatic#11753] opened 2023-01-25 08:17 UTC
installation of User Cluster MLA using Kubermatic installer: https://docs.kubermatic.com/kubermatic/main/tutorials-howtos/monitoring-logging-alerting/user-cluster/admin-guide/#installation
upgrade from the lastest version installed for 2.21: https://github.com/kubermatic/mla/releases/tag/v0.2.5 (install using https://docs.kubermatic.com/kubermatic/v2.21/tutorials-howtos/monitoring-logging-alerting/user-cluster/admin-guide/#installation)

**Comment by rastislavs** [comment] 2023-02-07 09:19
Upgrade eventually succeeded but it required several iterations and some manual steps. I think we need to at least update the upgrade docs a bit, not sure if anything else than documenting is possible:

**1. Attempt - Consul upgrade failed:**
```
./kubermatic-installer deploy usercluster-mla --config kubermatic.yaml --helm-values mlavalues.yaml                                                                                                         ✔
INFO[0000] 🚀 Initializing installer…                     edition="Enterprise Edition" version=v2.22.0-alpha.0
INFO[0000] 🚦 Validating the provided configuration…
INFO[0000] ✅ Provided configuration is valid.
INFO[0000] 🚦 Validating existing installation…
INFO[0000] ✅ Existing installation is valid.
INFO[0000] 🛫 Deploying KKP User Cluster MLA…
INFO[0000]    📦 Deploying MLA Secrets…
INFO[0001]    ⏭️  Skipped.
INFO[0001]    📦 Deploying Alertmanager Proxy…
INFO[0001]       Updating release from 0.2.1 to 2.22.0-alpha.0…
INFO[0010]    ✅ Success.
INFO[0010]    📦 Deploying Consul…
INFO[0010]       Updating release from 0.36.0 to 2.22.0-alpha.0…
ERRO[0015] ❌ Operation failed: failed to deploy Consul: failed to deploy Helm release: failed to install: WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /Users/rasto/Dev/kubeconfig.qa
Error: UPGRADE FAILED: release consul failed, and has been rolled back due to atomic being set: cannot patch "consul-consul-server" with kind StatefulSet: StatefulSet.apps "consul-consul-server" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden.
```

Can be resolved by uninstalling consul (`helm uninstall consul -n mla`) and re-running the installer.

**2. Attempt - Cortex installation time out:**
```
./kubermatic-installer deploy usercluster-mla --config kubermatic.yaml --helm-values mlavalues.yaml                                                                                                         ✔
INFO[0000] 🚀 Initializing installer…                     edition="Enterprise Edition" version=v2.22.0-alpha.0
INFO[0000] 🚦 Validating the provided configuration…
INFO[0000] ✅ Provided configuration is valid.
INFO[0000] 🚦 Validating existing installation…
INFO[0000] ✅ Existing installation is valid.
INFO[0000] 🛫 Deploying KKP User Cluster MLA…
INFO[0000]    📦 Deploying MLA Secrets…
INFO[0001]    ⏭️  Skipped.
INFO[0001]    📦 Deploying Alertmanager Proxy…
INFO[0001]       Release is up-to-date, nothing to do. Set --force to re-install anyway.
INFO[0001]    ✅ Success.
INFO[0001]    📦 Deploying Consul…
INFO[0041]    ✅ Success.
INFO[0041]    📦 Deploying Minio…
INFO[0042]       Downgrading release from 8.0.10 to 2.22.0-alpha.0…
INFO[0086]    ✅ Success.
INFO[0086]    📦 Deploying Cortex…
INFO[0086]       Updating release from 0.7.0 to 2.22.0-alpha.0…
ERRO[0750] ❌ Operation failed: failed to deploy Cortex: failed to deploy Helm release: failed to install: WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /Users/rasto/Dev/kubeconfig.qa
coalesce.go:220: warning: cannot overwrite table with non table for cortex.memcached.topologySpreadConstraints (map[])
W0207 08:52:58.773132   67825 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0207 08:52:58.875016   67825 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0207 08:58:00.552679   67825 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0207 08:58:00.587729   67825 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0207 08:58:00.632221   67825 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0207 08:58:00.663817   67825 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0207 08:58:00.691713   67825 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0207 08:58:00.733269   67825 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0207 08:58:00.761249   67825 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0207 08:58:00.790908   67825 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0207 08:58:00.840607   67825 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0207 08:58:00.871351   67825 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0207 08:58:00.908273   67825 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
Error: UPGRADE FAILED: an error occurred while rolling back the release. original upgrade error: timed out waiting for the condition: release cortex failed: Get "<redacted>": context deadline exceeded.
```

Here the problem is 5m timeout for the helm installation, which is not sufficient for Cortex (needs at least 3min per ingester = 9 mins). Can be documented by instructing the users to use non-default timeout: e.g. `--helm-timeout=15m0s`:
```
./kubermatic-installer deploy usercluster-mla --config kubermatic.yaml --helm-values mlavalues.yaml --helm-timeout=15m0s  
```

**3. Attempt - Loki upgrade failed:**
```
./kubermatic-installer deploy usercluster-mla --config kubermatic.yaml --helm-values mlavalues.yaml --helm-timeout=15m0s                                                                        1 ✘  12m 31s
INFO[0000] 🚀 Initializing installer…                     edition="Enterprise Edition" version=v2.22.0-alpha.0
INFO[0000] 🚦 Validating the provided configuration…
INFO[0000] ✅ Provided configuration is valid.
INFO[0000] 🚦 Validating existing installation…
INFO[0000] ✅ Existing installation is valid.
INFO[0000] 🛫 Deploying KKP User Cluster MLA…
INFO[0000]    📦 Deploying MLA Secrets…
INFO[0001]    ⏭️  Skipped.
INFO[0001]    📦 Deploying Alertmanager Proxy…
INFO[0001]       Release is up-to-date, nothing to do. Set --force to re-install anyway.
INFO[0001]    ✅ Success.
INFO[0001]    📦 Deploying Consul…
INFO[0002]       Release is up-to-date, nothing to do. Set --force to re-install anyway.
INFO[0002]    ✅ Success.
INFO[0002]    📦 Deploying Minio…
INFO[0003]       Re-installing because values have been changed…
INFO[0020]    ✅ Success.
INFO[0020]    📦 Deploying Cortex…
WARN[0021]       Uninstalling defunct release before a clean installation is attempted…
INFO[0022]       Release has been uninstalled.
INFO[0567]    ✅ Success.
INFO[0567]    📦 Deploying Grafana…
INFO[0567]       Downgrading release from 6.17.5 to 2.22.0-alpha.0…
INFO[0589]    ✅ Success.
INFO[0589]    📦 Deploying Loki…
INFO[0589]       Updating release from 0.39.0 to 2.22.0-alpha.0…

ERRO[1567] ❌ Operation failed: failed to deploy Loki: failed to deploy Helm release: failed to install: WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /Users/rasto/Dev/kubeconfig.qa
coalesce.go:220: warning: cannot overwrite table with non table for loki-distributed.loki-distributed.querier.affinity (map[])
coalesce.go:220: warning: cannot overwrite table with non table for loki-distributed.loki-distributed.querier.affinity (map[])
coalesce.go:220: warning: cannot overwrite table with non table for loki-distributed.loki-distributed.querier.affinity (map[])
W0207 09:29:18.132882   69113 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0207 09:29:18.193633   69113 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0207 09:29:18.242387   69113 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0207 09:29:18.273288   69113 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0207 09:29:18.306733   69113 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0207 09:29:18.465820   69113 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
Error: UPGRADE FAILED: release loki-distributed failed, and has been rolled back due to atomic being set: client rate limiter Wait returned an error: rate: Wait(n=1) would exceed context deadline.
```

Several loki pods (compactor, distributor, ingester, querier, ...) stuck in crashloop, with the following error in the logs:
```

level=error ts=2023-02-07T08:15:11.662677578Z caller=main.go:51 msg="validating config" err="invalid queryrange config: the yaml flag `split_queries_by_interval` must now be set in the `limits_config` section instead of the `query_range` config section"
```

Can be resolved by unsinstalling loki (`helm delete loki-distributed -n mla`) and re-running the installer.

**4. Attempt - success:**
```
./kubermatic-installer deploy usercluster-mla --config kubermatic.yaml --helm-values mlavalues.yaml --helm-timeout=15m0s                                                                                    ✔
INFO[0000] 🚀 Initializing installer…                     edition="Enterprise Edition" version=v2.22.0-alpha.0
INFO[0000] 🚦 Validating the provided configuration…
INFO[0000] ✅ Provided configuration is valid.
INFO[0000] 🚦 Validating existing installation…
INFO[0000] ✅ Existing installation is valid.
INFO[0000] 🛫 Deploying KKP User Cluster MLA…
INFO[0000]    📦 Deploying MLA Secrets…
INFO[0001]    ⏭️  Skipped.
INFO[0001]    📦 Deploying Alertmanager Proxy…
INFO[0003]       Release is up-to-date, nothing to do. Set --force to re-install anyway.
INFO[0003]    ✅ Success.
INFO[0003]    📦 Deploying Consul…
INFO[0004]       Release is up-to-date, nothing to do. Set --force to re-install anyway.
INFO[0004]    ✅ Success.
INFO[0004]    📦 Deploying Minio…
INFO[0004]       Re-installing because values have been changed…
INFO[0023]    ✅ Success.
INFO[0023]    📦 Deploying Cortex…
INFO[0024]       Release is up-to-date, nothing to do. Set --force to re-install anyway.
INFO[0024]    ✅ Success.
INFO[0024]    📦 Deploying Grafana…
INFO[0025]       Re-installing because values have been changed…
INFO[0032]    ✅ Success.
INFO[0032]    📦 Deploying Loki…
INFO[0104]    ✅ Success.
INFO[0104]    📦 Deploying Minio Bucket Lifecycle Manager…
INFO[0105]       Updating release from 0.1.0 to 2.22.0-alpha.0…
INFO[0106]    ✅ Success.
INFO[0106] 🛬 Installation completed successfully. Have a nice day!
```

**Comment by wurbanski** [comment] 2023-02-08 08:17
Thanks!

attempt 1 - this should be covered by the migration in the installer, I'll double check on that
attempt 2 - I will add this to the installation docs
attempt 3 - I will add this to the docs (moving the config option)
attempt 4 - 🎉

**Comment by rastislavs** [comment] 2023-02-08 09:02
@wurbanski when doing the docs update, could you also drop a note about values.yaml - and that values with something like:
```
---
```
can be provided if default values are desired?

**Comment by rastislavs** [comment] 2023-02-16 12:21
Upgrade works fine after the recent installer fixes.

**Closed as completed by rastislavs** 2023-02-16 12:21 UTC
