### ISSUE TITLE
Forbidden: Only values or valuesBlock can be set, but not both simultaneously / Invalid value: "null": value is immutable

### ISSUE THREAD

**Issue by judge-red** [kubermatic/kubermatic#13734] opened 2024-09-18 12:53 UTC
### What happened?

After upgrading to KKP 2.25.9, we see this Event in many UCs. It seems all UC using Cilium that existed before the upgrade are affected:

```
default              2m7s        Warning   ReconcilingError           cluster/nkfqdbmf8q                                              failed to ensure ApplicationInstallation kube-system/cilium: failed to update object *v1.ApplicationInstallation "kube-system/cilium": admission webhook "applicationinstallations.apps.kubermatic.k8c.io" denied the request: ApplicationInstallation validation request 4331e449-85f2-4d08-a932-2140f77b6707 denied: [spec.values: Forbidden: Only values or valuesBlock can be set, but not both simultaneously spec.valuesBlock: Forbidden: Only values or valuesBlock can be set, but not both simultaneously spec.values: Invalid value: "{\"certgen\":{\"podSecurityContext\":{\"seccompProfile\":{\"type\":\"RuntimeDefault\"}}},\"cni\":{\"exclusive\":false},\"hubble\":{\"relay\":{\"enabled\":true,\"podSecurityContext\":{\"seccompProfile\":{\"type\":\"RuntimeDefault\"}}},\"tls\":{\"auto\":{\"method\":\"cronJob\"}},\"ui\":{\"backend\":{},\"enabled\":true,\"frontend\":{},\"securityContext\":{\"seccompProfile\":{\"type\":\"RuntimeDefault\"}}}},\"ipam\":{\"operator\":{\"clusterPoolIPv4MaskSize\":\"24\",\"clusterPoolIPv4PodCIDRList\":[\"172.25.0.0/16\"]}},\"k8sServiceHost\":\"nkfqdbmf8q.os-zh.kaas.switch.ch\",\"k8sServicePort\":32561,\"kubeProxyReplacement\":\"strict\",\"operator\":{\"podSecurityContext\":{\"seccompProfile\":{\"type\":\"RuntimeDefault\"}},\"replicas\":1,\"securityContext\":{\"seccompProfile\":{\"type\":\"RuntimeDefault\"}}},\"podSecurityContext\":{\"seccompProfile\":{\"type\":\"RuntimeDefault\"}}}": unable to unmarshal values: the fields Values and ValuesBlock cannot be used simultaneously. Please delete one of them. spec.values.cni: Invalid value: "null": value is immutable spec.values.ipam: Invalid value: "null": value is immutable spec.values.kubeProxyReplacement: Not found: "null" spec.values.operator: Invalid value: "null": value missing or incorrect spec.values.operator.securityContext: Invalid value: "null": value is immutable]
```

One customer is reporting that connections are sporadically interrupted (not sure whether from or to the workload on the UC) but we can't be sure whether there's a connection.

### Expected behavior

No errors and no events.

### How to reproduce the issue?

Presumably:
- deploy KKP 2.25.8
- create UC with Cilium
- upgrade KKP to 2.25.9
- check UC for events

### How is your environment configured?

- KKP version: 2.25.9
- Shared or separate master/seed clusters?: shared

### Provide your KKP manifest here (if applicable)

N/A imho, let me know otherwise

### What cloud provider are you running on?

OpenStack

### What operating system are you running in your user cluster?

Ubuntu 22.04

### Additional information

Probably related to #13276 which was backported to 2.25.9 (#13702) without any notice in the changelog, thus we missed checking for problems on staging before rolling this out on production :(

**Comment by embik** [comment] 2024-09-18 13:47
Hey, we are investigating this issue.

**Comment by embik** [comment] 2024-09-18 14:30
Here's a preliminary analysis of the issue. A fix for it is under way at #13736. **The good news first, this SHOULD not have an active impact on clusters and their workloads** - We need to figure out with the issue's author what the reported network issues are, but so far it seems that Cilium should continue to run even if you are encountering this bug.

The problem is that the migration code in question is setting both `.spec.values` and `.spec.valuesBlock` when it was intended to only set `.spec.valuesBlock`. This is an invalid configuration and rejected by a webhook.

This means that the controller that maintains the cluster's `ApplicationInstallation` is failing to update said object. However, all logic "below" that (i.e. translating the existing `ApplicationInstallation` into a Helm chart, installing said chart and maintaining that Pods are running) **should continue to run fine** on the pre-migration `ApplicationInstallation` object.

We will backport the fix linked above once we've verified it and release a patch release for 2.25 as soon as we safely can.

**Comment by judge-red** [comment] 2024-09-18 14:46
> The good news first, this SHOULD not have an active impact on clusters and their workloads - We need to figure out with the issue's author what the reported network issues are, but so far it seems that Cilium should continue to run even if you are encountering this bug.

FWIW, I agree that these are separate issues and the network issue is probably a bug in the workload or most likely a resource shortage in the pod or on the worker node. I just wanted to include as much detail as I could and still get this reported ASAP, but I also see no connection between them at this time.

**Comment by xrstf** [comment] 2024-09-18 15:06
2.25.10 is planned for tomorrow (19th) to ship the fix.

Affected ApplicationInstallations can also be manually fixed by `kubectl -n kube-system edit applicationinstallations cilium` and replacing `values:` with `valuesBlock: |`, i.e. turning

```yaml
spec:
  values:
    foo: bar
```

into

```yaml
spec:
  valuesBlock: |
    foo: bar
```

(This is not officially recommended, just a technical note from me. ;-) )

**Comment by embik** [comment] 2024-09-19 10:20
The fix for this was unfortunately incomplete. We are observing new events of the format

```
failed to ensure ApplicationInstallation kube-system/cilium: failed waiting for the cache to contain our latest changes: context deadline exceeded
```

The migration is successfully applied (from `spec.values` to `spec.valuesBlock`), but an internal component fails to "realize" that the changes have been applied successfully. This moves the needle a little bit (successful migration, failing "status check"), but obviously we were hoping to provide a complete fix, not a partial one.

**Comment by judge-red** [comment] 2024-09-19 21:17
All looking good now, I think

**Comment by embik** [comment] 2024-09-20 06:15
Thank you for the feedback and patience. I will go ahead and close the issue again, for good this time.

/close

**Closed as completed by embik** 2024-09-20 06:15 UTC
Labels: kind/bug, sig/app-management
