### ISSUE TITLE
K8s minor version upgrade violates Kubernetes version skew policy

### ISSUE THREAD

**Issue by squ94wk** [kubermatic/kubermatic#7404] opened 2021-07-21 09:26 UTC
**Problem**
When upgrading a cluster to a new K8s minor version, all components get upgraded at once with no regard to their dependencies to apiserver.
More precisely, currently the apiserver update may only finish after the one from kube-controller-manager, kube-scheduler or cloud-controller-manager.
[Kubernetes Version Skew Policy](https://kubernetes.io/releases/version-skew-policy/#supported-component-upgrade-order) forbids this behavior.

**Bug**
This actually leads to a reproducible bug:

1. Create a cluster on 1.18.18
2. Pause the cluster
3. Upgrade kube-controller-manager to 1.19.7
4. Upgrade apiserver (and other components) to 1.19.7
5. Create new node

*** Expected behavior ***
Node joins cluster.

*** Actual behavior ***
Node can't join the cluster. Kubelet logs the following:
```
Jul 21 07:34:34 upgrade-1 kubelet[6446]: E0721 07:34:34.403716    6446 controller.go:136] failed to ensure node lease exists, will retry in 7s, error: leases.coordination.k8s.io "upgrade-1.19-test-worker-nc9nxn-c4669df4c-xx9qw" is forbidden: User "system:anonymous" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-node-lease"
[...]
Jul 21 07:34:34 upgrade-1 kubelet[6446]: I0721 07:34:34.870626    6446 kubelet_node_status.go:70] Attempting to register node upgrade-1.19-test-worker-nc9nxn-c4669df4c-xx9qw
Jul 21 07:34:34 upgrade-1 kubelet[6446]: E0721 07:34:34.873387    6446 kubelet_node_status.go:92] Unable to register node "upgrade-1.19-test-worker-nc9nxn-c4669df4c-xx9qw" with API server: nodes is forbidden: User "system:anonymous" cannot create resource "nodes" in API group "" at the cluster scope
```

After restarting kube-controller-manager, the node can finally join.

**Acceptance criteria**
- Any version updates for kube-controller-manager, kube-scheduler and cloud-controller-manager wait for apiserver to be updated to compatible version completely.

**Comment by irozzo-1A** [comment] 2021-07-21 16:01
Hi @squ94wk,

Closing this as duplicate of #5949.

**Closed as completed by irozzo-1A** 2021-07-21 16:01 UTC

**Comment by squ94wk** [comment] 2021-07-21 16:32
Thanks, I didn't find that issue before.
