### ISSUE TITLE
Test upgrading KKP

### ISSUE THREAD

**Issue by xrstf** [kubermatic/kubermatic#7658] opened 2021-09-03 13:19 UTC
### Steps

* Install KKP 2.17 using the KKP installer.
* Download the 2.18 rc release from GitHub.
* Use the 2.18 installer to upgrade the existing KKP setup.
* Verify that clusters, users and projects are still present.
* Check the logs of KKP components (kubermatic-master-controller-manager, kubermatic-seed-controller-manager, kubermatic-operator, usercluster-controller-manager) for errors.
* Create a new cluster and wait for it to become healthy.

### Acceptance Criteria
* KKP 2.18 systems works fine after being upgraded.

Part of #7655

**Comment by mfranczy** [comment] 2021-09-13 14:27
The upgrade worked well. I had an issue with missing telemetry charts (that's going to be fixed in the new rc tag) and issue with machines being rotated after changing replicas number. That's unexpected behaviour (it happens only if you change replicas of md - not right away after upgrade. It's caused by optional parameter that is not being used).

Additionaly we could make it more explicit how to turn off telemetry. Could be done in the upgrade doc.

I will retest the upgrade once we have a new rc tag.

**Comment by mfranczy** [comment] 2021-09-20 12:24
upgrade for 2.18.0 with standard setup works fine.

**Closed as completed by mfranczy** 2021-09-20 12:24 UTC
