### ISSUE TITLE
Application deployments lead into OOM

### ISSUE THREAD

**Issue by mate4st** [kubermatic/kubermatic#12078] opened 2023-03-21 15:25 UTC
### What happened?

A KKP user cluster with cilium deployed as an application has a crashlooping usercluster-cm. This is killed due to OOM reasons. 

This only occurs on clusters that are present for a longer period of time and with cilium as application installed. 

Further investigation showed that the Helm library is loading all helm revisions into memory to figure out the latest one. 
This includes metadata and the complete manifest of each revision. 
After checking the helm history on the cluster the problem is rather obvious: 

`kube-system-cilium	kube-system             	242     	2023-03-21 15:53:24.867538398 +0100 CET	failed  	cilium-1.13.0       	1.13.0     
`

Everytime the controller requests the last installed helm version it loads all 242+ versions with manifests in ram which explodes the controller. As the number of revisions grow over time, this explains why the controller did not show this error in short living clusters.

https://github.com/kubermatic/kubermatic/blob/main/pkg/applications/helmclient/client.go#L244

This is a helm implementation to load everything into ram and sort there.

### Expected behavior

We need to reduce the amount of revisions we create and cleanup old versions, so that we keep a maximum amount of revisions on the cluster. 

### How to reproduce the issue?

Reach out to @WeirdMachine

**Comment by embik** [comment] 2023-03-24 08:25
Do we have any idea how we ended up with 242 (!!) revisions? That seems a lot.

**Comment by vgramer** [comment] 2023-03-24 12:16
I would need more information about the cluster, but here are the "events" that trigger an upgrade. 

- change on the ApplicationDefinition or ApplicationInstallation CR 
- failure of the install/upgrade ( for cilium, timeout is set 10min)
- periodic reconciliation -> `.Spec.ReconciliationInterval` (set to 1h in case of cilium)
- restart of the userclsuter-controller

**Comment by embik** [comment] 2023-03-24 12:34
> periodic reconciliation -> .Spec.ReconciliationInterval (set to 1h in case of cilium)

This one trips me up a bit. Why would a reconciliation create a new revision if nothing in configuration failed?

**Comment by vgramer** [comment] 2023-03-24 13:16
Yes every time, you do a `helm upgrade`  a new revision is created even if the chart and values haven't changed. 

if the chart is well-written, it should not impact the workload. it will probably change some annotation at top level (i.e. deployment) but not rotate pods...

AFAIK it not possible to avoid creating a new revision.

**Comment by embik** [comment] 2023-03-24 13:39
Helm indeed cannot avoid creating a new revision when you run `helm upgrade`, but since it's very imperative by design I do think that our controllers (since they are working declaratively) need to include some additional logic (e.g. checking if the chart version changed or if values changed) that determines if the imperative step (i.e. running `helm upgrade`) needs to be run at all.

However that is probably out of scope for this fix, I can open a follow-up issue.

**Comment by vgramer** [comment] 2023-03-24 14:05
The main problem is that even if the chart and values haven't changed, the state of the cluster may have. For example, a user may intentionally or not delete or changes something (deployment, configMap....). 
So comparing the two release versions is not enough; we also need to check the cluster state. It's doable but there is probably a lot's of pitfall.

**Comment by embik** [comment] 2023-03-24 14:14
Very good point, another reason to move this to a separate issue. I will do so, thank you for the feedback!

**Comment by WeirdMachine** [comment] 2023-05-08 08:16
https://github.com/kubermatic/kubermatic/pull/12089

**Comment by embik** [comment] 2023-05-08 08:27
> Wasn't that fixed by: #12089 ?
> 
> Is there a backport missing?

Yeah, there is a 2.21 backport missing I think, since we added Application support during it and it can trigger issues like #12204.

**Comment by embik** [comment] 2023-05-12 08:00
2.21 backport is done in #12078. I'll close this ticket because I think we covered it across all affected releases.

**Closed as completed by embik** 2023-05-12 08:00 UTC
Labels: kind/bug, sig/app-management
