### ISSUE TITLE
api-server fails due to NetworkPolicy seed-apiserver-allow with Cilium

### ISSUE THREAD

**Issue by mihiragrawal** [kubermatic/kubermatic#12874] opened 2023-12-01 12:52 UTC
### What happened?

After upgrading to KKP `v2.24.0`, the user cluster api-server fails with the below error.
```
k logs -n cluster-espbj2d78g  apiserver-54f99cfff7-kkjf4 -c etcd-running -f
{"level":"error","time":"2023-11-30T10:43:46.518Z","caller":"etcd-launcher/main.go:116","msg":"Operation failed: failed to initialize etcd cluster configuration: failed to get API group resources: unable to retrieve the complete list of server APIs: kubermatic.k8c.io/v1: Get \"https://10.96.0.1:443/apis/kubermatic.k8c.io/v1\": dial tcp 10.96.0.1:443: i/o timeout."}
```

This is due to new network policy seed-apiserver-allow (https://github.com/kubermatic/kubermatic/pull/12569).

After pausing the cluster and removing the ipBlocks and, for example, only port 6443, it works.
```
  egress:
  - ports:
    - port: 6443
      protocol: TCP
  podSelector:
    matchLabels:
      app: apiserver
  policyTypes:
  - Egress
```

### Expected behavior

Running api-server

### How to reproduce the issue?

Upgrade to v2.24.0

### How is your environment configured?

- KKP version: v2.24.0
- Shared or separate master/seed clusters?: separate

### Provide your KKP manifest here (if applicable)

<details>

```yaml
# paste manifest here
```

</details>

**Comment by judge-red** [comment] 2023-12-01 13:58
I also see this issue after upgrading to 2.24.0. Both existing UCs and new UCs are affected.

**Comment by embik** [comment] 2023-12-01 14:26
Can someone affected please add how the NetworkPolicy actually looks like vs the endpoints the "kubernetes" Service has? Are they matching?

**Comment by judge-red** [comment] 2023-12-01 15:20
```
$ k -n cluster-afrxv2c5fh get networkpolicy seed-apiserver-allow -o yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: "2023-12-01T13:39:48Z"
  generation: 1
  name: seed-apiserver-allow
  namespace: cluster-afrxv2c5fh
  resourceVersion: "18776434"
  uid: 3d09a54f-663d-4571-8fcd-9ca9d89f6744
spec:
  egress:
  - to:
    - ipBlock:
        cidr: 192.168.0.10/32
    - ipBlock:
        cidr: 192.168.0.11/32
    - ipBlock:
        cidr: 192.168.0.12/32
  podSelector:
    matchLabels:
      app: apiserver
  policyTypes:
  - Egress
status: {}
```

```
$ k -n default get endpoints kubernetes
NAME         ENDPOINTS                                               AGE
kubernetes   192.168.0.10:6443,192.168.0.11:6443,192.168.0.12:6443   24d
```

No idea why it's not working, but I can confirm it works when adding port 6443/TCP like so:

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: "2023-12-01T13:39:48Z"
  generation: 5
  name: seed-apiserver-allow
  namespace: cluster-afrxv2c5fh
  resourceVersion: "18832308"
  uid: 3d09a54f-663d-4571-8fcd-9ca9d89f6744
spec:
  egress:
  - to:
    - ipBlock:
        cidr: 192.168.0.10/32
    - ipBlock:
        cidr: 192.168.0.11/32
    - ipBlock:
        cidr: 192.168.0.12/32
  - ports:
    - port: 6443
      protocol: TCP
  podSelector:
    matchLabels:
      app: apiserver
  policyTypes:
  - Egress
status: {}
```

**Comment by embik** [comment] 2023-12-05 08:29
> Upgrade to v2.24.0

@mihiragrawal this is insufficient for reproducing, as we have working environments internally (latest snapshot).

**Comment by embik** [comment] 2023-12-05 08:30
@judge-red what CNI is deployed on the underlying seed?

**Comment by judge-red** [comment] 2023-12-05 08:54
@embik Cilium, deployed with Kubeone 1.7.1

From the `kubeone.yaml`:
```
clusterNetwork:
  cni:
    cilium:
      enableHubble: true
      kubeProxyReplacement: strict
  kubeProxy:
    skipInstallation: true
```

**Comment by embik** [comment] 2023-12-05 09:14
Thanks, will try to reproduce based on that.

**Comment by embik** [comment] 2023-12-05 10:31
As per findings from @hc2p it looks like Cilium has a long-standing, well-known bug regarding this: https://github.com/cilium/cilium/issues/20550

**Comment by moadqassem** [comment] 2023-12-05 14:34
@judge-red Can you please check what is the service CIDR that cilium is using?

**Comment by embik** [comment] 2023-12-05 14:42
FYI, a possible workaround is to deploy a `CiliumNetworkPolicy` into each user cluster namespace:

```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: cilium-seed-apiserver-allow
spec:
  endpointSelector:
    matchLabels:
      app: apiserver
  egress:
  - toEntities:
    - kube-apiserver
  - toPorts:
    - ports:
      - port: "6443"
        protocol: TCP
```

**Comment by embik** [comment] 2023-12-06 14:16
Note: We plan to backport the PR linked above to 2.24 after validation.

**Comment by embik** [comment] 2023-12-08 10:37
#12892 reverts the PR closing this issue, reopening.

**Comment by embik** [comment] 2023-12-08 12:32
Update here as well: It's much easier to apply a single policy object per seed cluster that runs Cilium:

```yaml
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: cilium-seed-apiserver-allow
spec:
  egress:
  - toEntities:
    - kube-apiserver
  endpointSelector:
    matchLabels:
      app: apiserver
```

This policy applies to all user cluster apiservers at the same time, and thus doesn't need to be created upon cluster creation.

**Closed as completed** 2024-01-08 16:25 UTC
Labels: kind/bug, priority/high, sig/cluster-management, sig/networking, kind/regression
